name: "CD(continues deploy) pipeline"

on:
  push:
    tags:
      - v*

jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Firebase credential
        run: |
          echo '${{ secrets.CREDENTIAL }}' | base64 --decode | jq > ./src/credential.json

      - uses: jsryudev/deploy-firebase-functions@v18.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          FUNCTIONS_DIR: src
